### ISSUE TITLE
Query map was null.?

### ISSUE THREAD

**Issue by sologuy** [Tamicer/Novate#20]
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:776)
                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/Platform;
                                                                       at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:112)
                                                                       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:160)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                       at com.tamic.novate.CacheInterceptorOffline.intercept(CacheInterceptorOffline.java:69)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                       at com.tamic.novate.BaseInterceptor.intercept(BaseInterceptor.java:53)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                       at com.tamic.novate.BaseInterceptor.intercept(BaseInterceptor.java:53)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                       at okhttp3.RealCall.execute(RealCall.java:63)
                                                                       at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:111)
                                                                       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:92)
                                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                       at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                       at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                       at java.lang.Thread.run(Thread.java:776) 
05-18 15:49:28.894 14793-14954/com.lhdd.reading4 E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.internal.Platform" on path: DexPathList[[zip file "/data/app/com.lhdd.reading4-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lhdd.reading4-1/lib/arm64, /data/app/com.lhdd.reading4-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                       	... 42 more

**Comment by Tamicer** [comment]
@sologuy Retrofit老版本有个弊端 Map的值不能为空
