### ISSUE TITLE
使用当前库download方法的下载，出现问题

### ISSUE THREAD

**Issue by 2012xiaojuhua** [Tamicer/Novate#23]
我在下载文件后缀名是.mei文件的时候，点击下载报错
 FATAL EXCEPTION: RxIoScheduler-2
                                                                 Process: com.hxlm.leying, PID: 25979
                                                                 java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                  Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
                                                                     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
                                                                     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
                                                                     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:154)
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                                     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                  Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192) 
                                                                     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120) 
                                                                     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204) 
                                                                     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144) 
                                                                     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:154) 
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227) 
                                                                     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220) 
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                  Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                     at android.util.Log.getStackTraceString(Log.java:330)
                                                                     at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:59)
                                                                     at com.android.internal.os.RuntimeInit.access$200(RuntimeInit.java:43)
                                                                     at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:85)
                                                                     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.MediaType.toString()' on a null object reference
                                                                     at com.tamic.novate.download.NovateDownLoadManager.writeResponseBodyToDisk(NovateDownLoadManager.java:84)
                                                                     at com.tamic.novate.download.DownSubscriber.onNext(DownSubscriber.java:73)
                                                                     at com.tamic.novate.download.DownSubscriber.onNext(DownSubscriber.java:30)
                                                                     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:154)
                                                                     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                                     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                  Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6254)
                                                                     at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:867)
                                                                     at android.view.View.requestLayout(View.java:17372)
                                                                     at android.view.View.requestLayout(View.java:17372)
                                                                     at android.view.View.requestLayout(View.java:17372)
                                                                     at android.view.View.requestLayout(View.java:17372)
                                                                     at android.view.View.requestLayout(View.java:17372)
                                                                     at android.view.View.requestLayout(View.java:17372)
                                                                     at android.view.View.requestLayout(View.java:17372)
                                                                     at android.view.View.requestLayout(View.java:17372)
                                                                     at android.support.v7.widget.RecyclerView.requestLayout(RecyclerView.java:3080)
                                                                 	at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerV)

不知道什么原因造成，请有时间看看，多谢

**Comment by Tamicer** [comment]
@2012xiaojuhua 已更新至1.3.3 此类型已支持下载
