### ISSUE TITLE
会出现ANR异常啊，请求不是已经自动开线程了吗

### ISSUE THREAD

**Issue by huanyuan** [Tamicer/Novate#81]
"main" prio=5 tid=1 Suspended
  | group="main" sCount=1 dsCount=0 obj=0x743ae3b0 self=0xf5276500
  | sysTid=9774 nice=0 cgrp=default sched=0/0 handle=0xf7442b34
  | state=S schedstat=( 1889781210 434293032 1701 ) utm=163 stm=25 core=3 HZ=100
  | stack=0xff339000-0xff33b000 stackSize=8MB
  | held mutexes=
  at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
  - locked <0x01e7ce9a> (a java.util.concurrent.ConcurrentHashMap)
  at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
  at java.lang.reflect.Proxy.invoke(Proxy.java:393)
  at com.tamic.novate.BaseApiService.executePost(BaseApiService.java:-2)
  at com.tamic.novate.Novate.post(Novate.java:1179)
  at com.cyx.tvplayer.common.http.HttpManager.getCityBeanHttp(HttpManager.java:404)
  at com.cyx.tvplayer.Application.onCreate(Application.java:62)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4712)
  at android.app.ActivityThread.-wrap1(ActivityThread.java:-1)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5422)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Tamicer** [comment]
用rxPost.(),  老版本post()已经废弃了
